import Sidebar from "@/components/Sidebar/sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container h-full mx-auto xl:px-30 max-w-6xl">
          <div className="grid grid-cols-4 h-full">
            <Sidebar></Sidebar>
            <div className="col-span-3 lg:col-span-2 border-x-[1px] border-zinc-700">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
